### ISSUE TITLE
C# Type Color

### ISSUE THREAD

**Issue by JaimeStill** [HasseNasse/hyper-term-theme#1]
Hello, I would like to propose that the `storage.type.cs` scope be changed to match the stylings for classes in C#. I absolutely love this theme, and thus far, this is the only thing I've found that bugs me. Thanks for your work on this great extension!

``` json
"editor.tokenColorCustomizations": {
  "[Hyper Term Black]": {
    "textMateRules": [
      {
        "name": "csharp type",
        "scope": "storage.type.cs",
        "settings": {
          "foreground": "#e5c07b"
        }
      }
    ]
  }
}
```  

Please see below comparison:  

### Original Theme Settings  
![theme-original](https://user-images.githubusercontent.com/14102723/38438658-21042d68-39a9-11e8-8cb9-fb48b5c86b66.png)  

### Modified Theme Settings  
![theme-modded](https://user-images.githubusercontent.com/14102723/38438657-20f7f98a-39a9-11e8-8f59-9e8d9f172bb8.png)

**Comment by HasseNasse** [comment]
Hey @JaimeStill!
Happy you like the theme!
I have added C# type coloring on the 0.0.7 release of this theme.

Thanks for the feedback, happy coding!
