### ISSUE TITLE
Javascript colour

### ISSUE THREAD

**Issue by nrempel** [HasseNasse/hyper-term-theme#2]
Hello! I love this theme. Thanks for your work.

I've noticed that javascript has a lot of red colour:

https://www.dropbox.com/s/5va22ky6opoc7xj/Screenshot%202018-06-28%2010.41.58.png?dl=0

python looks a lot nicer:

https://www.dropbox.com/s/2m3pioskuu84lcm/Screenshot%202018-06-28%2010.43.32.png?dl=0

Is this intentional, or is it something that can be changed?

**Comment by HasseNasse** [comment]
Hello @nrempel !

Happy you like the theme :)
The JS syntax color scheme is intentional, however not bound to be the same forever ;)
I'm open for suggestions! Make changes to the source code and make a PR.

Regards

**Comment by nrempel** [comment]
Thanks @HasseNasse, I'll take a look soon.
